<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\EmbassyCity;

class EmbassyCitySeeder extends Seeder
{   
    public function run()
    {
        $embassyData = [
            'Afghanistan' => ['U.S. Embassy in Kabul'],
            'Albania' => ['U.S. Embassy in Tirana'],
            'Algeria' => ['U.S. Embassy in Algiers'],
            'Angola' => ['U.S. Embassy in Luanda'],
            'Argentina' => ['U.S. Embassy in Buenos Aires'],
            'Armenia' => ['U.S. Embassy in Yerevan'],
            'Australia' => ['Sydney', 'Melbourne', 'Perth'],
            'Austria' => ['U.S. Embassy in Vienna'],
            'Azerbaijan' => ['U.S. Embassy in Baku'],
            'Bahamas' => ['U.S. Embassy in Nassau'],
            'Bahrain' => ['U.S. Embassy in Manama'],
            'Bangladesh' => ['U.S. Embassy in Dhaka'],
            'Barbados' => ['U.S. Embassy in Bridgetown'],
            'Belarus' => ['U.S. Embassy in Minsk'],
            'Belgium' => ['U.S. Embassy in Brussels'],
            'Belize' => ['U.S. Embassy in Belmopan'],
            'Benin' => ['U.S. Embassy in Cotonou'],
            'Bermuda' => ['U.S. Consulate General in Hamilton'],
            'Bolivia' => ['U.S. Embassy in La Paz'],
            'Bosnia and Herzegovina' => ['U.S. Embassy in Sarajevo'],
            'Botswana' => ['U.S. Embassy in Gaborone'],
            'Brazil' => ['U.S. Embassy in Brasilia', 'U.S. Consulate General in Recife', 'U.S. Consulate General in Rio de Janeiro', 'U.S. Consulate General in Sao Paulo'],
            'Brunei' => ['U.S. Embassy in Bandar Seri Begawan'],
            'Bulgaria' => ['U.S. Embassy in Sofia'],
            'Burkina Faso' => ['U.S. Embassy in Ouagadougou'],
            'Burundi' => ['U.S. Embassy in Bujumbura'],
            'Cambodia' => ['U.S. Embassy in Phnom Penh'],
            'Cameroon' => ['U.S. Embassy in Yaounde'],
            'Canada' => ['U.S. Embassy in Ottawa', 'U.S. Consulate General in Calgary', 'U.S. Consulate General in Halifax', 'U.S. Consulate General in Montreal', 'U.S. Consulate General in Quebec', 'U.S. Consulate General in Toronto', 'U.S. Consulate General in Vancouver'],
            'Cape Verde' => ['U.S. Embassy in Praia'],
            'Central African Republic' => ['U.S. Embassy in Bangui'],
            'Chad' => ['U.S. Embassy in N\'Djamena'],
            'Chile' => ['U.S. Embassy in Santiago'],
            'China' => ['U.S. Embassy in Beijing', 'U.S. Consulate General in Guangzhou', 'U.S. Consulate General in Shanghai', 'U.S. Consulate General in Shenyang', 'U.S. Consulate General in Wuhan', 'U.S. Consulate General in Hong Kong & Macau'],
            'Colombia' => ['U.S. Embassy in Bogota'],
            'Congo' => ['U.S. Embassy in Brazzaville'],
            'Congo (Kinshasa)' => ['U.S. Embassy in Kinshasa'],
            'Costa Rica' => ['U.S. Embassy in San Jose'],
            'Cote d\'Ivoire' => ['U.S. Embassy in Abidjan'],
            'Croatia' => ['U.S. Embassy in Zagreb'],
            'Cuba' => ['U.S. Embassy in Havana'],
            'Cyprus' => ['U.S. Embassy in Nicosia'],
            'Czech Republic' => ['U.S. Embassy in Prague'],
            'Denmark' => ['U.S. Embassy in Copenhagen'],
            'Djibouti' => ['U.S. Embassy in Djibouti'],
            'Dominican Republic' => ['U.S. Embassy in Santo Domingo'],
            'Ecuador' => ['U.S. Embassy in Quito', 'U.S. Consulate General in Guayaquil'],
            'Egypt' => ['U.S. Embassy in Cairo'],
            'El Salvador' => ['U.S. Embassy in San Salvador'],
            'Equatorial Guinea' => ['U.S. Embassy in Malabo'],
            'Eritrea' => ['U.S. Embassy in Asmara'],
            'Estonia' => ['U.S. Embassy in Tallinn'],
            'Ethiopia' => ['U.S. Embassy in Addis Ababa'],
            'Fiji' => ['U.S. Embassy in Suva'],
            'Finland' => ['U.S. Embassy in Helsinki'],
            'France' => ['U.S. Embassy in Paris'],
            'Gabon' => ['U.S. Embassy in Libreville'],
            'Gambia' => ['U.S. Embassy in Banjul'],
            'Georgia' => ['U.S. Embassy in Tbilisi'],
            'Germany' => ['U.S. Embassy in Berlin', 'U.S. Consulate General in Frankfurt', 'U.S. Consulate General in Munich'],
            'Ghana' => ['U.S. Embassy in Accra'],
            'Greece' => ['U.S. Embassy in Athens'],
            'Guatemala' => ['U.S. Embassy in Guatemala City'],
            'Guinea' => ['U.S. Embassy in Conakry'],
            'Guyana' => ['U.S. Embassy in Georgetown'],
            'Haiti' => ['U.S. Embassy in Port-au-Prince'],
            'Honduras' => ['U.S. Embassy in Tegucigalpa'],
            'Hungary' => ['U.S. Embassy in Budapest'],
            'Iceland' => ['U.S. Embassy in Reykjavik'],
            'India' => ['U.S. Embassy in New Delhi', 'U.S. Consulate General in Chennai', 'U.S. Consulate General in Hyderabad', 'U.S. Consulate General in Kolkata', 'U.S. Consulate General in Mumbai'],
            'Indonesia' => ['U.S. Embassy in Jakarta', 'U.S. Consulate General in Surabaya'],
            'Iraq' => ['U.S. Embassy in Baghdad', 'U.S. Consulate General in Erbil'],
            'Ireland' => ['U.S. Embassy in Dublin'],
            'Israel' => ['U.S. Embassy in Jerusalem'],
            'Italy' => ['U.S. Embassy in Rome', 'U.S. Consulate General in Florence', 'U.S. Consulate General in Milan', 'U.S. Consulate General in Naples'],
            'Jamaica' => ['U.S. Embassy in Kingston'],
            'Japan' => ['U.S. Embassy in Tokyo', 'U.S. Consulate General in Naha', 'U.S. Consulate General in Osaka-Kobe', 'U.S. Consulate General in Sapporo', 'U.S. Consulate General in Fukuoka'],
            'Jordan' => ['U.S. Embassy in Amman'],
            'Kazakhstan' => ['U.S. Embassy in Nur-Sultan', 'U.S. Consulate General in Almaty'],
            'Kenya' => ['U.S. Embassy in Nairobi'],
            'Kosovo' => ['U.S. Embassy in Pristina'],
            'Kuwait' => ['U.S. Embassy in Kuwait City'],
            'Kyrgyzstan' => ['U.S. Embassy in Bishkek'],
            'Laos' => ['U.S. Embassy in Vientiane'],
            'Latvia' => ['U.S. Embassy in Riga'],
            'Lebanon' => ['U.S. Embassy in Beirut'],
            'Lesotho' => ['U.S. Embassy in Maseru'],
            'Liberia' => ['U.S. Embassy in Monrovia'],
            'Libya' => ['U.S. Embassy in Tripoli'],
            'Lithuania' => ['U.S. Embassy in Vilnius'],
            'Luxembourg' => ['U.S. Embassy in Luxembourg'],
            'Madagascar' => ['U.S. Embassy in Antananarivo'],
            'Malawi' => ['U.S. Embassy in Lilongwe'],
            'Malaysia' => ['U.S. Embassy in Kuala Lumpur'],
            'Mali' => ['U.S. Embassy in Bamako'],
            'Malta' => ['U.S. Embassy in Valletta'],
            'Marshall Islands' => ['U.S. Embassy in Majuro'],
            'Mauritania' => ['U.S. Embassy in Nouakchott'],
            'Mauritius' => ['U.S. Embassy in Port Louis'],
            'Mexico' => ['U.S. Embassy in Mexico City', 'U.S. Consulate General in Ciudad Juarez', 'U.S. Consulate General in Guadalajara', 'U.S. Consulate General in Hermosillo', 'U.S. Consulate General in Matamoros', 'U.S. Consulate General in Merida', 'U.S. Consulate General in Monterrey', 'U.S. Consulate General in Nogales', 'U.S. Consulate General in Nuevo Laredo', 'U.S. Consulate General in Tijuana'],
            'Micronesia' => ['U.S. Embassy in Kolonia'],
            'Moldova' => ['U.S. Embassy in Chisinau'],
            'Mongolia' => ['U.S. Embassy in Ulaanbaatar'],
            'Montenegro' => ['U.S. Embassy in Podgorica'],
            'Morocco' => ['U.S. Embassy in Rabat', 'U.S. Consulate General in Casablanca'],
            'Mozambique' => ['U.S. Embassy in Maputo'],
            'Namibia' => ['U.S. Embassy in Windhoek'],
            'Nepal' => ['U.S. Embassy in Kathmandu'],
            'Netherlands' => ['U.S. Consulate General in Amsterdam'],
            'New Zealand' => ['U.S. Consulate General in Auckland'],
            'Nicaragua' => ['U.S. Embassy in Managua'],
            'Niger' => ['U.S. Embassy in Niamey'],
            'Nigeria' => ['U.S. Embassy in Abuja', 'U.S. Consulate General in Lagos'],
            'North Macedonia' => ['U.S. Embassy in Skopje'],
            'Norway' => ['U.S. Embassy in Oslo'],
            'Oman' => ['U.S. Embassy in Muscat'],
            'Pakistan' => ['U.S. Embassy in Islamabad', 'U.S. Consulate General in Karachi'],
            'Palau' => ['U.S. Embassy in Koror'],
            'Panama' => ['U.S. Embassy in Panama City'],
            'Papua New Guinea' => ['U.S. Embassy in Port Moresy'],
            'Paraguay' => ['U.S. Embassy in Asuncion'],
            'Peru' => ['U.S. Embassy in Lima'],
            'Philippines' => ['U.S. Embassy in Manila'],
            'Poland' => ['U.S. Embassy in Warsaw', 'U.S. Consulate General in Krakow'],
            'Portugal' => ['U.S. Embassy in Lisbon', 'U.S. Consulate in Ponta Delgada'],
            'Qatar' => ['U.S. Embassy in Doha'],
            'Romania' => ['U.S. Embassy in Bucharest'],
            'Russia' => ['U.S. Embassy in Moscow'],
            'Rwanda' => ['U.S. Embassy in Kigali'],
            'Samoa' => ['U.S. Embassy in Apia'],
            'Saudi Arabia' => ['U.S. Embassy in Riyadh', 'U.S. Consulate General in Dhahran', 'U.S. Consulate General in Jeddah'],
            'Senegal' => ['U.S. Embassy in Dakar'],
            'Serbia' => ['U.S. Embassy in Belgrade'],
            'Sierra Leone' => ['U.S. Embassy in Freetown'],
            'Singapore' => ['U.S. Embassy in Singapore'],
            'Slovakia' => ['U.S. Embassy in Bratislava'],
            'Slovenia' => ['U.S. Embassy in Ljubljana'],
            'South Africa' => ['U.S. Embassy in Pretoria', 'U.S. Consulate General in Cape Town', 'U.S. Consulate General in Durban', 'U.S. Consulate General in Johannesburg'],
            'South Korea' => ['U.S. Embassy in Seoul'],
            'South Sudan' => ['U.S. Embassy in Juba'],
            'Spain' => ['U.S. Embassy in Madrid'],
            'Sri Lanka' => ['U.S. Embassy in Colombo'],
            'Sudan' => ['U.S. Embassy in Khartoum'],
            'Suriname' => ['U.S. Embassy in Paramaribo'],
            'Swaziland' => ['U.S. Embassy in Mbabane'],
            'Sweden' => ['U.S. Embassy in Stockholm'],
            'Switzerland' => ['U.S. Embassy in Bern'],
            'Syria' => ['U.S. Embassy in Damascus'],
            'Taiwan' => ['American Institute in Taiwan, Taipei', 'American Institute in Taiwan, Kaohsiung'],
            'Tajikistan' => ['U.S. Embassy in Dushanbe'],
            'Tanzania' => ['U.S. Embassy in Dar es Salaam'],
            'Thailand' => ['U.S. Embassy in Bangkok', 'U.S. Consulate General in Chiang Mai'],
            'Timor-Leste' => ['U.S. Embassy in Dili'],
            'Togo' => ['U.S. Embassy in Lome'],
            'Trinidad and Tobago' => ['U.S. Embassy in Port of Spain'],
            'Tunisia' => ['U.S. Embassy in Tunis'],
            'Turkey' => ['U.S. Embassy in Ankara', 'U.S. Consulate General in Istanbul'],
            'Turkmenistan' => ['U.S. Embassy in Ashgabat'],
            'Uganda' => ['U.S. Embassy in Kampala'],
            'Ukraine' => ['U.S. Embassy in Kyiv'],
            'United Arab Emirates' => ['U.S. Embassy in Abu Dhabi', 'U.S. Consulate General in Dubai'],
            'United Kingdom' => ['U.S. Embassy in London', 'U.S. Consulate General in Belfast'],
            'Uruguay' => ['U.S. Embassy in Montevideo'],
            'Uzbekistan' => ['U.S. Embassy in Tashkent'],
            'Venezuela' => ['U.S. Embassy in Caracas'],
            'Vietnam' => ['U.S. Embassy in Hanoi', 'U.S. Consulate General in Ho Chi Minh City'],
            'Yemen' => ['U.S. Embassy in Sana\'a'],
            'Zambia' => ['U.S. Embassy in Lusaka'],
            'Zimbabwe' => ['U.S. Embassy in Harare'],
        ];

        foreach ($embassyData as $countryName => $cityNames) {
            $country = \App\Models\Country::where('name', $countryName)->first();
            
            if ($country) {
                foreach ($cityNames as $cityName) {
                    EmbassyCity::updateOrCreate(
                        [
                            'name' => $cityName,
                            'parent_id' => $country->id,
                        ],
                        []
                    );
                }
            }
        }
    }
}
