<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\EmbassyCity;

class EmbassyCitySeeder extends Seeder
{   
    public function run()
    {
        $cities = [
            ['name' => 'U.S. Embassy in Kabul', 'parent_id' =>   1],    
            ['name' => 'U.S. Embassy in Tirana', 'parent_id' =>   2],    
            ['name' => 'U.S. Embassy in Algiers', 'parent_id' =>   3],    
            ['name' => 'U.S. Embassy in Angola', 'parent_id' =>   6],    
            ['name' => 'U.S. Embassy in Buenos Aires', 'parent_id' =>  10],    
            ['name' => 'U.S. Embassy in Yerevan', 'parent_id' =>  11],    
            ['name' => 'U.S. Embassy in Canberra', 'parent_id' =>  13],    
            ['name' => 'U.S. Embassy in Melbourne', 'parent_id' =>  13],    
            ['name' => 'U.S. Embassy in Perth', 'parent_id' =>  13],    
            ['name' => 'U.S. Embassy in Sydney', 'parent_id' =>  13],    
            ['name' => 'U.S. Embassy in Vienna', 'parent_id' =>  14],    
            ['name' => 'U.S. Embassy in Baku', 'parent_id' =>  15],    
            ['name' => 'U.S. Mission to ASEAN', 'parent_id' =>  15],    
            ['name' => 'U.S. Mission to Asean in Indonesia', 'parent_id' =>  15],    
            ['name' => 'U.S. Mission to the African Union', 'parent_id' =>  15],    
            ['name' => 'U.S. Mission to the African Union in Ethiopia', 'parent_id' =>  15],    
            ['name' => 'U.S. Embassy in Nassau', 'parent_id' =>  16],    
            ['name' => 'U.S. Embassy in Manama', 'parent_id' =>  17],    
            ['name' => 'U.S. Embassy in Dhaka', 'parent_id' =>  18],    
            ['name' => 'U.S. Embassy in Barbados', 'parent_id' =>  19],    
            ['name' => 'U.S. Embassy in Minsk', 'parent_id' =>  20],    
            ['name' => 'U.S. Embassy in Minsk', 'parent_id' =>  20],    
            ['name' => 'U.S. Embassy in Brussels', 'parent_id' =>  21],    
            ['name' => 'U.S. Embassy in Belmopan', 'parent_id' =>  22],    
            ['name' => 'U.S. Embassy in Cotonou, Benin', 'parent_id' =>  23],    
            ['name' => 'U.S. Embassy in Hamilton', 'parent_id' =>  24],    
            ['name' => 'U.S. Embassy in La Paz', 'parent_id' =>  26],    
            ['name' => 'U.S. Embassy in Saravejo', 'parent_id' =>  27],    
            ['name' => 'U.S. Embassy in Gaborone', 'parent_id' =>  28],    
            ['name' => 'U.S. Embassy in Brasillia', 'parent_id' =>  30],    
            ['name' => 'U.S. Consulate in Porto Alegre', 'parent_id' =>  30],    
            ['name' => 'U.S. Consulate General in Recife', 'parent_id' =>  30],    
            ['name' => 'U.S. Consulate General in Rio de Janeiro', 'parent_id' =>  30],    
            ['name' => 'U.S. Consulate General in Sao Paulo', 'parent_id' =>  30],    
            ['name' => 'U.S. Embassy in Bandar Seri Begawan', 'parent_id' =>  32],    
            ['name' => 'U.S. Embassy in Sofia', 'parent_id' =>  33],    
            ['name' => 'U.S. Embassy in Ouagadougou', 'parent_id' =>  34],    
            ['name' => 'U.S. Embassy in Rangoon', 'parent_id' => 247],    
            ['name' => 'U.S. Embassy in Bujumbura', 'parent_id' =>  35],    
            ['name' => 'U.S. Embassy in Praia', 'parent_id' => 248],    
            ['name' => 'U.S. Embassy in Phnom Penh', 'parent_id' =>  36],    
            ['name' => 'U.S. Embassy in Yaounde', 'parent_id' =>  37],    
            ['name' => 'U.S. Embassy in Ottawa', 'parent_id' =>  38],    
            ['name' => 'U.S. Consulate General in Calgary', 'parent_id' =>  38],    
            ['name' => 'U.S. Consulate General in Halifax', 'parent_id' =>  38],    
            ['name' => 'U.S. Consulate General in Montreal', 'parent_id' =>  38],    
            ['name' => 'U.S. Consulate General in Quebec', 'parent_id' =>  38],    
            ['name' => 'U.S. Consulate General in Toronto', 'parent_id' =>  38],    
            ['name' => 'U.S. Consulate General in Vancouver', 'parent_id' =>  38],    
            ['name' => 'U.S. Consulate in Winnipeg', 'parent_id' =>  38],    
            ['name' => 'U.S. Embassy in Bangui', 'parent_id' =>  41],    
            ['name' => "U.S. Embassy in N'Djamena", 'parent_id' =>  42],    
            ['name' => 'U.S. Embassy in Santiago', 'parent_id' =>  43],    
            ['name' => 'U.S. Embassy in Beijing', 'parent_id' =>  44],    
            ['name' => 'U.S. Consulate in Chengdu', 'parent_id' =>  44],    
            ['name' => 'U.S. Consulate General in Guangzhou', 'parent_id' =>  44],    
            ['name' => 'U.S. Consulate inShanghai', 'parent_id' =>  44],    
            ['name' => 'U.S. Consulate General in Wuhan', 'parent_id' =>  44],    
            ['name' => 'U.S. Embassy in Bogota', 'parent_id' =>  47],    
            ['name' => 'U.S. Embassy in San Jose', 'parent_id' =>  52],    
            ['name' => 'U.S. Embassy in Abidjan', 'parent_id' =>  53],    
            ['name' => 'U.S. Embassy in Zagreb', 'parent_id' =>  54],    
            ['name' => 'U.S. Embassy in Havana', 'parent_id' =>  55],    
            ['name' => 'U.S. Consulate General in Curacao', 'parent_id' => 249],    
            ['name' => 'U.S. Embassy in Nicosia', 'parent_id' =>  56],    
            ['name' => 'U.S. Embassy in Prague', 'parent_id' =>  57],    
            ['name' => 'U.S. Embassy in Kinshasa', 'parent_id' =>  50],    
            ['name' => 'U.S. Embassy in Copenhagen', 'parent_id' =>  58],    
            ['name' => 'U.S. Embassy in Djibouti', 'parent_id' =>  59],    
            ['name' => 'U.S. Embassy in Santo Domingo', 'parent_id' =>  61],    
            ['name' => 'U.S. Embassy in Quito', 'parent_id' =>  63],    
            ['name' => 'U.S. Consulate General in Guayaquil', 'parent_id' =>  63],    
            ['name' => 'U.S. Embassy in Cairo', 'parent_id' =>  64],    
            ['name' => 'U.S. Consulate General in Alexandria', 'parent_id' =>  64],    
            ['name' => 'U.S. Embassy in San Salvador', 'parent_id' =>  65],    
            ['name' => 'U.S. Embassy in Malabo', 'parent_id' =>  66],    
            ['name' => 'U.S. Embassy in Asmara', 'parent_id' =>  67],    
            ['name' => 'U.S. Embassy in Tallinn', 'parent_id' =>  68],    
            ['name' => 'U.S. Embassy in Mbabane', 'parent_id' => 250],    
            ['name' => 'U.S. Embassy in Addis Ababa', 'parent_id' =>  69],    
            ['name' => 'U.S. Mission to the EU', 'parent_id' =>  69],    
            ['name' => 'U.S. Mission to the EU in Brussels, Belgium', 'parent_id' =>  69],    
            ['name' => 'U.S. Embassy in Suva', 'parent_id' =>  73],    
            ['name' => 'U.S. Embassy in Helsinki', 'parent_id' =>  74],    
            ['name' => 'U.S. Embassy in Paris', 'parent_id' =>  75],    
            ['name' => 'U.S. Consulate Bordeaux', 'parent_id' =>  75],    
            ['name' => 'U.S. Consulate Lyon', 'parent_id' =>  75],    
            ['name' => 'U.S. Consulate General Marseille', 'parent_id' =>  75],    
            ['name' => 'U.S. Consulate Rennes', 'parent_id' =>  75],    
            ['name' => 'U.S. Consulate General Strasbourg', 'parent_id' =>  75],    
            ['name' => 'U.S. Consulate Toulouse', 'parent_id' =>  75],    
            ['name' => 'U.S. Embassy in Libreville', 'parent_id' =>  79],    
            ['name' => 'U.S. Embassy in Banjul', 'parent_id' =>  80],    
            ['name' => 'U.S. Embassy in Tbilisi', 'parent_id' =>  81],    
            ['name' => 'U.S. Embassy in Berlin', 'parent_id' =>  82],    
            ['name' => 'U.S. Consulate General in Dusseldorf', 'parent_id' =>  82],    
            ['name' => 'U.S. Consulate General in Frankfurt', 'parent_id' =>  82],    
            ['name' => 'U.S. Consulate General in Hamburg', 'parent_id' =>  82],    
            ['name' => 'U.S. Consulate General in Leipzig', 'parent_id' =>  82],    
            ['name' => 'U.S. Consulate General in Munich', 'parent_id' =>  82],    
            ['name' => 'U.S. Embassy in Athens', 'parent_id' =>  85],    
            ['name' => 'U.S. Consulate in Thessaloniki', 'parent_id' =>  85],    
            ['name' => 'U.S. Embassy in Guatemala City', 'parent_id' =>  90],    
            ['name' => 'U.S. Embassy in Conakry', 'parent_id' =>  92],    
            ['name' => 'U.S. Virtual Consulate in Guinea-Bissau', 'parent_id' =>  93],    
            ['name' => 'U.S. Embassy in Georgetown', 'parent_id' =>  94],    
            ['name' => 'U.S. Embassy in Port Au Prince', 'parent_id' =>  95],    
            ['name' => 'U.S. Embassy to the Holy See', 'parent_id' => 236],    
            ['name' => 'U.S. Embassy in Tegucigalpa', 'parent_id' =>  97],    
            ['name' => 'U.S. Consulate General in Hong Kong', 'parent_id' =>  98],    
            ['name' => 'U.S. Consulate General in Hong Kong', 'parent_id' => 128],    
            ['name' => 'U.S. Embassy in Budapest', 'parent_id' =>  99],    
            ['name' => 'U.S. Embassy in Reykjavik', 'parent_id' => 100],    
            ['name' => 'U.S. Embassy in New Delhi', 'parent_id' => 101],    
            ['name' => 'U.S. Consulate General in Chennai', 'parent_id' => 101],    
            ['name' => 'U.S. Consulate General in Hyderabad', 'parent_id' => 101],    
            ['name' => 'U.S. Consulate General in Kolkata', 'parent_id' => 101],    
            ['name' => 'U.S. Consulate General in Mumbai', 'parent_id' => 101],    
            ['name' => 'U.S. Embassy in Jakarta', 'parent_id' => 102],    
            ['name' => 'U.S. Consulate General in Surabaya', 'parent_id' => 102],    
            ['name' => 'U.S. Consulate in Medan', 'parent_id' => 102],    
            ['name' => 'U.S. Consular Agency in Bali', 'parent_id' => 102],    
            ['name' => 'U.S. Embassy in Tehran', 'parent_id' => 103],    
            ['name' => 'U.S. Embassy in Baghdad', 'parent_id' => 104],    
            ['name' => 'U.S. Consulate General in Basrah', 'parent_id' => 104],    
            ['name' => 'U.S. Consulate General in Erbil', 'parent_id' => 104],    
            ['name' => 'U.S. Embassy in Dublin', 'parent_id' => 105],    
            ['name' => 'U.S. Embassy in Jerusalem', 'parent_id' => 106],    
            ['name' => 'U.S. Embassy in Rome', 'parent_id' => 107],    
            ['name' => 'U.S. Consulate General in Florence', 'parent_id' => 107],    
            ['name' => 'U.S. Consulate General in Milan', 'parent_id' => 107],    
            ['name' => 'U.S. Consulate General in Naples', 'parent_id' => 107],    
            ['name' => 'U.S. Mission to the ICAO', 'parent_id' => 107],    
            ['name' => 'U.S. Mission to the ICAO in Montreal Canada', 'parent_id' => 107],    
            ['name' => 'U.S. Embassy in Kingston', 'parent_id' => 108],    
            ['name' => 'U.S. Embassy in Tokyo', 'parent_id' => 109],    
            ['name' => 'U.S. Consulate in Fukuoka', 'parent_id' => 109],    
            ['name' => 'U.S. Consulate in Nagoya', 'parent_id' => 109],    
            ['name' => 'U.S. Consulate in Naha', 'parent_id' => 109],    
            ['name' => 'U.S. Consulate in Osaka', 'parent_id' => 109],    
            ['name' => 'U.S. Consulate General in Sapporo', 'parent_id' => 109],    
            ['name' => 'U.S. Consulate General in Jerusalem', 'parent_id' => 251],    
            ['name' => 'U.S. Embassy in Amman', 'parent_id' => 111],    
            ['name' => 'U.S. Embassy in Astana', 'parent_id' => 112],    
            ['name' => 'U.S. Embassy in Nairobi', 'parent_id' => 113],    
            ['name' => 'U.S. Embassy in Seoul', 'parent_id' => 114],    
            ['name' => 'U.S. Consulate in Busan', 'parent_id' => 114],    
            ['name' => 'U.S. Embassy in Pristina', 'parent_id' => 252],    
            ['name' => 'U.S. Embassy Kuwait City', 'parent_id' => 117],    
            ['name' => 'U.S. Embassy in Bishkek', 'parent_id' => 118],    
            ['name' => 'U.S. Embassy in Vientiane', 'parent_id' => 119],    
            ['name' => 'U.S. Embassy in Riga', 'parent_id' => 120],    
            ['name' => 'U.S. Embassy in Beirut', 'parent_id' => 121],    
            ['name' => 'U.S. Embassy in Maseru', 'parent_id' => 122],    
            ['name' => 'U.S. Embassy in Monrovia', 'parent_id' => 123],    
            ['name' => 'U.S. Embassy in Tripoli', 'parent_id' => 124],    
            ['name' => 'U.S. Embassy in Vilnius', 'parent_id' => 126],    
            ['name' => 'U.S. Embassy in Luxembourg', 'parent_id' => 127],    
            ['name' => 'U.S. Embassy in Antananarivo', 'parent_id' => 130],    
            ['name' => 'U.S. Embassy in Antananarivo', 'parent_id' => 130],    
            ['name' => 'U.S. Embassy in Antananarivo', 'parent_id' =>  48],    
            ['name' => 'U.S. Embassy in Lilongwe', 'parent_id' => 131],    
            ['name' => 'U.S. Embassy in Kuala Lumpur', 'parent_id' => 132],    
            ['name' => 'U.S. Virtual Mission in Maldives', 'parent_id' => 133],    
            ['name' => 'U.S. Embassy in Bamako', 'parent_id' => 134],    
            ['name' => 'U.S. Embassy in Valletta', 'parent_id' => 135],    
            ['name' => 'U.S. Embassy in Majuro', 'parent_id' => 137],    
            ['name' => 'U.S. Embassy in Nouakchott', 'parent_id' => 139],    
            ['name' => 'U.S. Embassy in Port Louis', 'parent_id' => 140],    
            ['name' => 'U.S. Embassy in Mexico City', 'parent_id' => 142],    
            ['name' => 'U.S. Consulate General in Ciudad Juarez', 'parent_id' => 142],    
            ['name' => 'U.S. Consulate General in Guadalajara', 'parent_id' => 142],    
            ['name' => 'U.S. Consulate General in Hermosillo', 'parent_id' => 142],    
            ['name' => 'U.S. Consulate General in Matamoros', 'parent_id' => 142],    
            ['name' => 'U.S. Consulate General in Merida', 'parent_id' => 142],    
            ['name' => 'U.S. Consulate General in Monterrey', 'parent_id' => 142],    
            ['name' => 'U.S. Consulate General in Mogales', 'parent_id' => 142],    
            ['name' => 'U.S. Consulate General in Nuevo Laredo', 'parent_id' => 142],    
            ['name' => 'U.S. Consulate General in Tijuana', 'parent_id' => 142],    
            ['name' => 'U.S. Embassy in Kolonia', 'parent_id' => 143],    
            ['name' => 'U.S. Embassy in Chisinau', 'parent_id' => 144],    
            ['name' => 'U.S. Embassy in Ulaanbaatar', 'parent_id' => 146],    
            ['name' => 'U.S. Embassy in Podgorica', 'parent_id' => 253],    
            ['name' => 'U.S. Embassy Rabat', 'parent_id' => 148],    
            ['name' => 'U.S. Consulate General Casablanca', 'parent_id' => 148],    
            ['name' => 'U.S. Embassy in Maputo', 'parent_id' => 149],    
            ['name' => 'U.S. Embassy in Windhoek', 'parent_id' => 151],    
            ['name' => 'High Commission of Australia in Nauru', 'parent_id' => 152],    
            ['name' => 'High Commission of Canada in Canberra, Australia', 'parent_id' => 152],    
            ['name' => 'U.S. Embassy in Kathmandu', 'parent_id' => 153],    
            ['name' => 'U.S. Embassy in The Hague', 'parent_id' => 155],    
            ['name' => 'U.S. Consulate General in Amsterdam', 'parent_id' => 155],    
            ['name' => 'U.S. Consulate General in Curacao', 'parent_id' => 154],    
            ['name' => 'U.S. Embassy in Wellington', 'parent_id' => 157],    
            ['name' => 'U.S. Consulate General in Auckland', 'parent_id' => 157],    
            ['name' => 'U.S. Embassy in Managua', 'parent_id' => 158],    
            ['name' => 'U.S. Embassy in Niamey', 'parent_id' => 159],    
            ['name' => 'U.S. Embassy in Abuja', 'parent_id' => 160],    
            ['name' => 'U.S. Consulate Lagos', 'parent_id' => 160],    
            ['name' => 'U.S. Embassy in Skopje', 'parent_id' => 129],    
            ['name' => 'U.S. Embassy in Oslo', 'parent_id' => 164],    
            ['name' => 'U.S. Mission to NATO', 'parent_id' => 164],    
            ['name' => 'U.S. Mission to Nato in Belgium', 'parent_id' => 164],    
            ['name' => 'U.S. Embassy in Muscat', 'parent_id' => 165],    
            ['name' => 'U.S. Mission to OSCE', 'parent_id' => 165],    
            ['name' => 'U.S. Mission to the OSCE in Vienna, Austria', 'parent_id' => 165],    
            ['name' => 'U.S. Mission to the OAS', 'parent_id' => 165],    
            ['name' => 'U.S. Mission to the OAS in Washington D.C.', 'parent_id' => 165],    
            ['name' => 'U.S. Mission to the OECD', 'parent_id' => 165],    
            ['name' => 'U.S. Mission to the OECD in Paris, France', 'parent_id' => 165],    
            ['name' => 'U.S. Embassy in Islamabad', 'parent_id' => 166],    
            ['name' => 'U.S. Consulate General in Karachi', 'parent_id' => 166],    
            ['name' => 'U.S. Consulate General in Lahore', 'parent_id' => 166],    
            ['name' => 'U.S. Consulate General in Peshawar', 'parent_id' => 166],    
            ['name' => 'U.S. Embassy in Koror', 'parent_id' => 167],    
            ['name' => 'U.S. Embassy in Panama City', 'parent_id' => 169],    
            ['name' => 'U.S. Embassy in Port Moresby', 'parent_id' => 170],    
            ['name' => 'U.S. Embassy in Asuncion', 'parent_id' => 171],    
            ['name' => 'U.S. Embassy in Lima', 'parent_id' => 172],    
            ['name' => 'U.S. Embassy in Manila', 'parent_id' => 173],    
            ['name' => 'U.S. Embassy in Warsaw', 'parent_id' => 175],    
            ['name' => 'U.S. Consulate General in Krakow', 'parent_id' => 175],    
            ['name' => 'Consular Agency in Poznan', 'parent_id' => 175],    
            ['name' => 'U.S. Embassy in Lisbon', 'parent_id' => 176],    
            ['name' => 'U.S. Consulate Ponta Delgada Azore', 'parent_id' => 176],    
            ['name' => 'U.S. Embassy in Doha', 'parent_id' => 178],    
            ['name' => 'U.S. Embassy in Brazzaville', 'parent_id' =>  49],    
            ['name' => 'U.S. Embassy in Bucharest', 'parent_id' => 180],    
            ['name' => 'U.S. Embassy in Moscow', 'parent_id' => 181],    
            ['name' => 'U.S. Consulate General in Vladivostok', 'parent_id' => 181],    
            ['name' => 'U.S. Consulate General in Yekaterinburg', 'parent_id' => 181],    
            ['name' => 'U.S. Embassy in Kigali', 'parent_id' => 182],    
            ['name' => 'U.S. Embassy in Apia', 'parent_id' => 188],    
            ['name' => 'U.S. Embassy in San Marino', 'parent_id' => 189],    
            ['name' => 'U.S. Embassy in Riyadh', 'parent_id' => 191],    
            ['name' => 'U.S. Consulate General in Dhahran', 'parent_id' => 191],    
            ['name' => 'U.S. Consulate General in Jeddah', 'parent_id' => 191],    
            ['name' => 'U.S. Embassy in Dakar', 'parent_id' => 192],    
            ['name' => 'U.S. Embassy in Belgrade', 'parent_id' => 193],    
            ['name' => 'U.S. Embassy in Freetown', 'parent_id' => 195],    
            ['name' => 'U.S. Embassy in Singapore', 'parent_id' => 196],    
            ['name' => 'U.S. Embassy in Bratislava', 'parent_id' => 197],    
            ['name' => 'U.S. Embassy in Ljubljana', 'parent_id' => 198],    
            ['name' => 'U.S. Mission to Somalia', 'parent_id' => 201],    
            ['name' => 'U.S. Embassy in Pretoria', 'parent_id' => 202],    
            ['name' => 'U.S. Consulate General in Cape Town', 'parent_id' => 202],    
            ['name' => 'U.S. Embassy in U.S. Consulate General in Durban', 'parent_id' => 202],    
            ['name' => 'U.S. Consulate General in Johannesburg', 'parent_id' => 202],    
            ['name' => 'U.S. Embassy in Juba', 'parent_id' => 204],    
            ['name' => 'U.S. Embassy in Madrid', 'parent_id' => 205],    
            ['name' => 'U.S. Consulate in Barcelona', 'parent_id' => 205],    
            ['name' => 'U.S. Embassy in Colombo', 'parent_id' => 206],    
            ['name' => 'U.S. Embassy in Khartoum', 'parent_id' => 207],    
            ['name' => 'U.S. Embassy in Paramaribo', 'parent_id' => 208],    
            ['name' => 'U.S. Embassy in Stockholm', 'parent_id' => 211],    
            ['name' => 'U.S. Embassy in Bern', 'parent_id' => 211],    
            ['name' => 'U.S. Virtual Mission Liechtenstein', 'parent_id' => 211],    
            ['name' => 'U.S. Embassy in Damascus', 'parent_id' => 213],    
            ['name' => 'American Institute in Taiwan', 'parent_id' => 214],    
            ['name' => 'Kaohsiung Branch Office in Kaohsiung', 'parent_id' => 214],    
            ['name' => 'U.S. Embassy in Dushanbe', 'parent_id' => 215],    
            ['name' => 'U.S. Embassy in Dar es Salaam', 'parent_id' => 216],    
            ['name' => 'U.S. Embassy in Bangkok', 'parent_id' => 217],    
            ['name' => 'U.S. Consulate General Chiang Mai', 'parent_id' => 217],    
            ['name' => 'U.S. Embassy in Dili', 'parent_id' =>  62],    
            ['name' => 'U.S. Embassy in Lome', 'parent_id' => 218],    
            ['name' => 'U.S. Embassy in Tonga', 'parent_id' => 220],    
            ['name' => 'U.S. Embassy in Port of Spain', 'parent_id' => 221],    
            ['name' => 'U.S. Embassy in Tunis', 'parent_id' => 222],    
            ['name' => 'U.S. Embassy in Ankara', 'parent_id' => 223],    
            ['name' => 'U.S. Consulate General in Istanbul', 'parent_id' => 223],    
            ['name' => 'U.S. Consulate in Adana', 'parent_id' => 223],    
            ['name' => 'U.S. Embassy in Ashgabat', 'parent_id' => 224],    
            ['name' => 'U.S. Mission to the UN - Geneva', 'parent_id' => 224],    
            ['name' => 'U.S. Mission in Geneva Switzerland', 'parent_id' => 224],    
            ['name' => 'U.S. Mission to the UN - Rome', 'parent_id' => 224],    
            ['name' => 'U.S. Mission in Rome, Italy', 'parent_id' => 224],    
            ['name' => 'U.S. Mission to the United Nations', 'parent_id' => 224],    
            ['name' => 'U.S. Mission to the United Nations in New York, New York', 'parent_id' => 224],    
            ['name' => 'U.S. Mission to UNESCO', 'parent_id' => 224],    
            ['name' => 'U.S. Mission to UNESCO in Paris, France', 'parent_id' => 224],    
            ['name' => 'U.S. Embassy in Kampala', 'parent_id' => 227],    
            ['name' => 'U.S. Embassy in Kyiv', 'parent_id' => 228],    
            ['name' => 'U.S. Embassy in Abu Dhabi', 'parent_id' => 229],    
            ['name' => 'Embassy of the United States of America', 'parent_id' => 230],    
            ['name' => 'U.S. Consulate General in Belfast', 'parent_id' => 230],    
            ['name' => 'U.S. Consulate General in Edinburgh', 'parent_id' => 230],    
            ['name' => 'U.S. Embassy Montevideo', 'parent_id' => 233],    
            ['name' => 'U.S. Embassy in Tashkent', 'parent_id' => 234],    
            ['name' => 'U.S. Mission to International Organizations in Vienna', 'parent_id' => 234],    
            ['name' => 'U.S. Mission to the International Organizations in Vienna, Austria', 'parent_id' => 234],    
            ['name' => 'U.S. Embassy in Caracas', 'parent_id' => 237],    
            ['name' => 'U.S. Embassy in Hanoi', 'parent_id' => 238],    
            ['name' => 'U.S. Consulate in Ho Chi Minh City', 'parent_id' => 238],    
            ['name' => "U.S. Embassy in Sana'a", 'parent_id' => 243],    
            ['name' => 'U.S. Embassy in Lusaka', 'parent_id' => 245],    
            ['name' => 'U.S. Embassy in Harare', 'parent_id' => 246],    
        ];        
        foreach ($cities as $cityData) {           
            if (!EmbassyCity::where('name', $cityData['name'])->where('parent_id', $cityData['parent_id'])->exists()) {
                EmbassyCity::create($cityData);
            }
        }
    }
}
